import { boolean, date, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core"

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow() })
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }) })
export const authAccount = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt", { withTimezone: true }), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow() })

export const crmAccounts = pgTable("crm_accounts", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), ownerUserId: text("owner_user_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("crm_accounts_owner_idx").on(table.ownerUserId)])
export const profiles = pgTable("profiles", { id: uuid("id").primaryKey().defaultRandom(), userId: text("user_id").notNull(), accountId: uuid("account_id").notNull(), fullName: text("full_name").notNull(), email: text("email").notNull(), avatarUrl: text("avatar_url"), accountRole: text("account_role").notNull().default("owner"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("profiles_user_idx").on(table.userId)])
export const contacts = pgTable("contacts", { id: uuid("id").primaryKey().defaultRandom(), userId: text("user_id").notNull(), accountId: uuid("account_id").notNull(), phone: text("phone").notNull(), name: text("name"), email: text("email"), company: text("company"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const pipelines = pgTable("pipelines", { id: uuid("id").primaryKey().defaultRandom(), userId: text("user_id").notNull(), accountId: uuid("account_id").notNull(), name: text("name").notNull(), position: integer("position").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const pipelineStages = pgTable("pipeline_stages", { id: uuid("id").primaryKey().defaultRandom(), pipelineId: uuid("pipeline_id").notNull(), name: text("name").notNull(), position: integer("position").notNull().default(0), color: text("color").notNull().default("#3b82f6"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() })
export const deals = pgTable("deals", { id: uuid("id").primaryKey().defaultRandom(), userId: text("user_id").notNull(), accountId: uuid("account_id").notNull(), pipelineId: uuid("pipeline_id").notNull(), stageId: uuid("stage_id").notNull(), contactId: uuid("contact_id"), assignedTo: uuid("assigned_to"), title: text("title").notNull(), value: numeric("value", { precision: 12, scale: 2 }).notNull().default("0"), currency: text("currency").default("USD"), company: text("company"), priority: text("priority").notNull().default("normal"), probability: integer("probability").notNull().default(0), leadSource: text("lead_source"), lastActivity: text("last_activity"), nextStep: text("next_step"), description: text("description"), notes: text("notes"), expectedCloseDate: date("expected_close_date"), status: text("status").default("active"), position: integer("position").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const pipelineSavedViews = pgTable("pipeline_saved_views", { id: uuid("id").primaryKey().defaultRandom(), accountId: uuid("account_id").notNull(), pipelineId: uuid("pipeline_id").notNull(), createdBy: text("created_by").notNull(), name: text("name").notNull(), filters: jsonb("filters").notNull().default({}), sort: jsonb("sort").notNull().default({}), visibleFields: text("visible_fields").array().notNull().default([]), isFavorite: boolean("is_favorite").notNull().default(false), position: integer("position").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const subPipelines = pgTable("sub_pipelines", { id: uuid("id").primaryKey().defaultRandom(), accountId: uuid("account_id").notNull(), pipelineId: uuid("pipeline_id").notNull(), name: text("name").notNull(), position: integer("position").notNull().default(0), createdBy: text("created_by").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const subPipelineDeals = pgTable("sub_pipeline_deals", { accountId: uuid("account_id").notNull(), subPipelineId: uuid("sub_pipeline_id").notNull(), dealId: uuid("deal_id").notNull(), position: integer("position").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [primaryKey({ columns: [table.subPipelineId, table.dealId] })])
