import { Client } from 'pg';
const c = new Client({ connectionString: (process.env.POSTGRES_URL_NON_POOLING || process.env.POSTGRES_URL).replace(/[?&]sslmode=[^&]*/,''), ssl:{rejectUnauthorized:false} });
await c.connect();
const q = async (label, sql) => { try { const r = await c.query(sql); console.log('\n==', label); console.table(r.rows); } catch(e){ console.log('\n==',label,'ERR',e.message); } };
await q('profiles', `select p.user_id, p.email, p.account_id, a.name account_name, p.account_role, p.status, p.workspace_profile_id, wp.name wp_name, p.workspace_role_id from profiles p left join accounts a on a.id=p.account_id left join workspace_profiles wp on wp.id=p.workspace_profile_id where p.email in ('admin@gmail.com','admin1@gmail.com')`);
await q('memberships tables', `select table_name from information_schema.tables where table_schema='public' and table_name like '%member%'`);
await q('account_members', `select * from account_members limit 20`);
await q('accounts', `select id,name,owner_user_id from accounts`);
await q('workspace_profiles', `select id,account_id,name,is_system from workspace_profiles order by account_id`);
await c.end();
